create table if not exists locations (
  location_id int generated by default as identity primary key,
  location_uuid uuid not null default gen_random_uuid(),
  user_id int not null references users (user_id) on delete cascade,
  coordinates geography(point, 4326) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create unique index if not exists location_uuid_idx on locations (location_uuid);
create index if not exists location_user_id_idx on locations (user_id);
