create table if not exists family_members (
  family_member_id int generated by default as identity primary key,
  user_id int not null references users (user_id) on delete cascade,
  family_id int not null references families (family_id) on delete cascade,
  created_at timestamp with time zone not null default current_timestamp
);

create index if not exists family_member_user_id_idx on family_members (user_id);
create index if not exists family_member_family_id_idx on family_members (family_id);
