create table if not exists users (
  user_id int generated by default as identity primary key,
  user_uuid uuid not null default gen_random_uuid(),
  email varchar(255) unique not null check (length(email) >= 5),
  password_digest varchar(255) not null,
  first_name varchar(64) not null,
  last_name varchar(64) not null,
  avatar varchar(255),
  created_at timestamp with time zone not null default current_timestamp,
  updated_at timestamp with time zone not null default current_timestamp,
  is_deleted boolean not null default false
);

create unique index if not exists user_uuid_idx on users (user_uuid);
create unique index if not exists user_email_idx on users (email);

create or replace function set_updated_columns()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_update_users
before update on users
for each row execute procedure set_updated_columns();
