create table if not exists families (
  family_id int generated by default as identity primary key,
  family_uuid uuid not null default gen_random_uuid(),
  name varchar(64) not null check (length(name) >= 2),
  created_by int references users (user_id) on delete set null,
  created_at timestamp with time zone not null default current_timestamp,
  updated_at timestamp with time zone not null default current_timestamp,
  is_deleted boolean not null default false
);

create unique index if not exists family_uuid_idx on families (family_uuid);

create trigger on_update_families
before update on families
for each row execute procedure set_updated_columns();
