create table if not exists sessions (
  session_id int generated by default as identity primary key,
  user_id int not null references users (user_id) on delete cascade,
  refresh_token uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default current_timestamp,
  updated_at timestamp with time zone not null default current_timestamp
);

create unique index if not exists session_refresh_token_idx on sessions (refresh_token);

create trigger on_update_sessions
before update on sessions
for each row execute procedure set_updated_columns();
