definitions:
  models.Access:
    properties:
      accessToken:
        type: string
      expiry:
        type: string
      refreshToken:
        type: string
    type: object
  models.Family:
    properties:
      createdAt:
        type: string
      createdBy:
        type: string
      id:
        type: string
      isDeleted:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
    type: object
  models.FamilyMember:
    properties:
      createdAt:
        type: string
      family:
        type: string
      user:
        type: string
    type: object
  models.Health:
    properties:
      status:
        type: string
    type: object
  models.Location:
    properties:
      createdAt:
        type: string
      id:
        type: string
      lat:
        type: number
      lon:
        type: number
      user:
        type: string
    type: object
  models.Media:
    properties:
      contentType:
        type: string
      createdAt:
        type: string
      id:
        type: string
      size:
        type: integer
    type: object
  models.NewFamily:
    properties:
      name:
        type: string
    type: object
  models.NewLocation:
    properties:
      lat:
        type: number
      lon:
        type: number
    type: object
  models.NewUser:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
    type: object
  models.Refresh:
    properties:
      refreshToken:
        type: string
    type: object
  models.SignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.SyncData:
    properties:
      families:
        items:
          $ref: '#/definitions/models.Family'
        type: array
      familyMembers:
        items:
          $ref: '#/definitions/models.FamilyMember'
        type: array
      locations:
        items:
          $ref: '#/definitions/models.Location'
        type: array
      users:
        items:
          $ref: '#/definitions/models.User'
        type: array
    type: object
  models.UpdateUser:
    properties:
      avatar:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    type: object
  models.User:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      isDeleted:
        type: boolean
      lastName:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: Web API for Tribe Tracker
  title: Tribe Tracker API
  version: 1.0.0
paths:
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh an existing token.
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Refresh'
      produces:
      - application/json
      responses:
        "201":
          description: User access and refresh tokens
          schema:
            $ref: '#/definitions/models.Access'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: RefreshToken
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user.
      parameters:
      - description: User details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.NewUser'
      produces:
      - application/json
      responses:
        "201":
          description: Newly created user access and refresh tokens
          schema:
            $ref: '#/definitions/models.Access'
        "400":
          description: Bad request
          schema:
            type: string
        "409":
          description: Email already in use
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Register user
      tags:
      - Auth
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Sign in to an existing account.
      parameters:
      - description: User details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignIn'
      produces:
      - application/json
      responses:
        "201":
          description: User access and refresh tokens
          schema:
            $ref: '#/definitions/models.Access'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Sign in
      tags:
      - Auth
  /api/families:
    post:
      consumes:
      - application/json
      description: Create a new family.
      parameters:
      - description: Family details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.NewFamily'
      produces:
      - application/json
      responses:
        "201":
          description: Newly created family
          schema:
            $ref: '#/definitions/models.Family'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create family
      tags:
      - Family
  /api/families/{familyId}:
    get:
      description: Get family details.
      parameters:
      - description: Family ID
        in: path
        name: familyId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Family details
          schema:
            $ref: '#/definitions/models.Family'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Family not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get family
      tags:
      - Family
  /api/families/{familyId}/members:
    get:
      description: Get all members of a family.
      parameters:
      - description: Family ID
        in: path
        name: familyId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Family members
          schema:
            items:
              $ref: '#/definitions/models.FamilyMember'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Family not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get family members
      tags:
      - Family
    post:
      description: Join a family.
      parameters:
      - description: Family ID
        in: path
        name: familyId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Newly created family member
          schema:
            $ref: '#/definitions/models.FamilyMember'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Family not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create family member
      tags:
      - Family
  /api/families/{familyId}/members/locations:
    get:
      description: Get all member locations for a family.
      parameters:
      - description: Family ID
        in: path
        name: familyId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Family member locations
          schema:
            items:
              $ref: '#/definitions/models.Location'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Family not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get family member locations
      tags:
      - Family
  /api/health:
    get:
      description: Get service health state.
      produces:
      - text/plain
      responses:
        "200":
          description: Service health
          schema:
            $ref: '#/definitions/models.Health'
        "404":
          description: Router failed
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get service health
      tags:
      - Meta
  /api/locations:
    post:
      consumes:
      - application/json
      description: Create a new location.
      parameters:
      - description: Family details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.NewLocation'
      produces:
      - application/json
      responses:
        "201":
          description: Newly created family
          schema:
            $ref: '#/definitions/models.Location'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create location
      tags:
      - Location
  /api/media:
    post:
      consumes:
      - multipart/form-data
      description: Create a new media file.
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created media
          schema:
            $ref: '#/definitions/models.Media'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create media
      tags:
      - Media
  /api/media/{mediaId}:
    get:
      description: Get media file.
      parameters:
      - description: Media ID
        in: path
        name: mediaId
        required: true
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: Media file
          schema:
            type: file
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Media not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get media
      tags:
      - Media
  /api/sync:
    get:
      description: Get recent sync data.
      parameters:
      - description: After
        in: query
        name: after
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sync data
          schema:
            $ref: '#/definitions/models.SyncData'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get sync data
      tags:
      - Sync
  /api/users/me:
    get:
      description: Get the calling user.
      produces:
      - application/json
      responses:
        "200":
          description: Calling user
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get me
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Update the calling user.
      parameters:
      - description: User details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: Updated user
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "409":
          description: Email already in use
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Update me
      tags:
      - User
swagger: "2.0"
